name: dennis
favicon: null
layout_spectrum: 0.5653185623232275
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f46d2a'
    - '#000000'
    - '#eb3816'
    - '#e0b49d'
  brandStrength: 0.3125
  lightness: 0.5003219444770366
  saturation: 0.5638674094807357
  rhythmicContrast: 0.5173228580970317
purpose: []
